### ISSUE TITLE
can not use raw in join statement

### ISSUE THREAD

**Issue by ecemerimguner** [sqbjs/sqb#22]
input:

select(
    'BOOK_ID', 'WRITER.NAME', 'BOOK.STOCK'
).from('BOOK ')
    .join(
        sqb.raw('inner join WRITER on BOOK.BOOK_ID = WRITER.WRITER_ID')
    )

output:
TypeError: Invalid argument in method "join"

**Comment by erayhanoglu** [comment]
join method does not accept Raw objects. We can add this functionality in next releases.
