### ISSUE TITLE
procedure join

### ISSUE THREAD

**Issue by ecemerimguner** [sqbjs/sqb#24]
I write procedure this way 
INPUT:
select('B.BOOK_ID', 'a.NAME').from('BOOK B')
    .join(
        sqb.leftOuterJoin(**raw('table (getBook(B.YEAR,WRITER_ID)) a on 1=1')**)
  )
Is there any easier way to cover all databases?

**Comment by erayhanoglu** [comment]
We may make an implementation for procedure calls next releases.
