### ISSUE TITLE
Module cannot be loaded in Node version 12.16+

### ISSUE THREAD

**Issue by glasseyes42** [sqbjs/sqb#30]
Simply requiring the module in nodejs version 12.16 causes failure.
`const sqb = require('sqb');`
the error is:
```
.../node_modules/sqb/lib/helper/aggregation.js:50
          if (prop.match(/^(?:initializer|constructor|prototype|arguments|caller|name|bind|call|apply|toString|length)$/))
                   ^

TypeError: prop.match is not a function
```

ie, here: https://github.com/sqbjs/sqb/blob/master/lib/helper/aggregation.js#L50

By adding a couple of lines of code to log out type and name we found the error came from a Symbol:
```
string constructor
string _events
string _eventsCount
string _maxListeners
string setMaxListeners
string getMaxListeners
string emit
string addListener
string on
string prependListener
string once
string prependOnceListener
string removeListener
string off
string removeAllListeners
string listeners
string rawListeners
string listenerCount
string eventNames
symbol Symbol(kCapture)
.../node_modules/sqb/lib/helper/aggregation.js:51
          if (prop.match(/^(?:initializer|constructor|prototype|arguments|caller|name|bind|call|apply|toString|length)$/))
```

The only reference to this `kCapture` we found was in https://github.com/nodejs/node/pull/27867/files - something included in node 12.16, which ties this all together.

`Symbol.match` does not appear to exist, hence the break.

**Comment by erayhanoglu** [comment]
Hello. Just published 3.9.2. This should fix the problem.
