### ISSUE TITLE
PrimaryKey field name change bug

### ISSUE THREAD

**Issue by mutavci** [sqbjs/sqb#33]
# Bug Report

### 🔎 Search Terms

`sqb id fieldName change error`, `primary key`

### 🕗 Version & Regression Information
   "@sqb/builder": "^4.0.1-alpha.18",
    "@sqb/connect": "^4.0.1-alpha.18",
    "@sqb/nestjs": "^4.0.1-alpha.18",
    "@sqb/oracle": "^4.0.1-alpha.18",
    "@sqb/oracle-dialect": "^4.0.1-alpha.18",
    "@sqb/postgres": "^4.0.1-alpha.18",
    "@sqb/postgres-dialect": "^4.0.1-alpha.18",

### 💻 Code

```ts
    @PrimaryKey()
    @Column({fieldName:'pk', update: false, insert: false})
    @AutoGenerated('increment')
    id: number = 0;
```

### 🙁 Actual behavior
Doesn't change the id field
```sql
update patients set given_name = $1, family_name = $2 where id = $3
```

### 🙂 Expected behavior

```sql
update patients set given_name = $1, family_name = $2 where pk = $3
```

**Comment by erayhanoglu** [comment]
Resolved in Alpha.19
