### ISSUE TITLE
Type 'time' can not inserted to postgresql db

### ISSUE THREAD

**Issue by MuminCelal** [sqbjs/sqb#38]
**Database definition**
---
<img width="328" alt="Screen Shot 2021-04-05 at 11 25 25" src="https://user-images.githubusercontent.com/15386828/113554368-e4a3b600-9601-11eb-9399-5c883432fe45.png">

**Entity definition**
---
<img width="328" alt="Screen Shot 2021-04-05 at 11 25 46" src="https://user-images.githubusercontent.com/15386828/113554423-f84f1c80-9601-11eb-91c9-9498d8eeb720.png">

**Test result**
---
<img width="951" alt="Screen Shot 2021-04-05 at 11 26 09" src="https://user-images.githubusercontent.com/15386828/113554598-38ae9a80-9602-11eb-9156-df679805d44a.png">

**Comment by erayhanoglu** [comment]
This issue is related to the postgresql-client driver. Please open issue into https://github.com/panates/postgresql-client repository
