### ISSUE TITLE
Data insertion failing without 'id' PK

### ISSUE THREAD

**Issue by MuminCelal** [sqbjs/sqb#39]
if `id` PK is not specified explicitly in the database, data insertion is failing and sqb is returning `Unable to insert new row`.

**Database structure that causing insertion problem**
---
![Screen Shot 2021-04-05 at 15 45 22](https://user-images.githubusercontent.com/15386828/113575558-b8e6f700-9626-11eb-9b27-68e21f6879e2.png)

When I debug the code marked as _1_ and as _2_ code lines the following picture is returning undefined.

<img width="506" alt="Screen Shot 2021-04-05 at 15 54 17" src="https://user-images.githubusercontent.com/15386828/113576356-1a5b9580-9628-11eb-98ca-41bbc229abad.png">

**Converted database structure that not causing insertion problem**
---
![Screen Shot 2021-04-05 at 15 46 35](https://user-images.githubusercontent.com/15386828/113575682-ec298600-9626-11eb-9266-7e56551ef726.png)

if `id` is inserted into the database structure then like the above picture then marked as _1_ and as _2_ code lines are not returning undefined (returning `id`) and insertion completed successfully.

**Comment by erayhanoglu** [comment]
It seems your table has no primary key. So SQB can not fetch row after insert. If you add a primary key to your table it will work as expected.
