### ISSUE TITLE
Implement "sequence" support

### ISSUE THREAD

**Issue by ahincalan** [sqbjs/sqb#5]
For use in "Insert" or "Update" statement

**Comment by erayhanoglu** [comment]
Did you mean using that you need a serializer function to get sequence values in statements?
eg. may be we can use an SqlObject like this.
`select(sqb.sequence('ID_SEQ'), 'name').from('table')`

or we can create a macro sub system for such kind of needing.
`macro(name, ...params)`
`select(sqb.macro('sequence', 'ID_SEQ'), 'name').from('table')`

what do you think?
